version: "3.6"

services:
  account:
    tty: true
    build:
      context: "."
      dockerfile: "./account/app.dockerfile"
    ports:
      - "8000:8080"
    volumes:
      - ./account:/go/src/app
    depends_on:
      - "account_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@account_db/spidey?sslmode=disable"

  account_db:
    build:
      context: "./account"
      dockerfile: "db.dockerfile"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"
